### ISSUE TITLE
Harmony fails to generate code.

### ISSUE THREAD

**Issue by youpko** [Microchip-MPLAB-Harmony/bootloader#12]
The Harmony Bootloader (v3.5.0) fails to generate code with the following error:
```
<FreeMarker>[Error]: An exception was thrown while attempting to markup a template file: F:\Toolchain\Hardware\Mircochip\Harmony\bootloader\templates\system\tasks.c.ftl
<FreeMarker>[Error]: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> BTL_RTOS_STACK_SIZE  [in template "tasks.c.ftl" at line 4, column 32]

----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign BTL_STACK_SIZE = (BTL_RTOS_ST...  [in template "tasks.c.ftl" at line 4, column 5]
----
<FreeMarker>[Error]: 	- Failed at: #assign BTL_STACK_SIZE = (BTL_RTOS_ST...  [in template "tasks.c.ftl" at line 4, column 5]
<Generate>[Error]: MHC Code Generation failed.
```

I have created a new project for the PIC32MZ1024EFK064, Added the **File System Bootloader** module and its required components. but it fails to generate any code with the above mentioned error.

**Comment by amitraddi** [comment]
HI @youpko 
Thanks for Reporting.
Currently we do not support RTOS for  **File system Bootloader**, so if you have added FreeRTOS in your project graph please remove it and it will resolve the error.

We will add a safety check in next release to avoid these generation errors

**Comment by youpko** [comment]
I added FreeRTOS because I thought is was a dependency for the Harmony Core serverces, but I see now that is an optional dependency. I can confirm that removing FreeRTOS did the trick and everything get generated fine.

**Comment by amitraddi** [comment]
Closing the issue as removing FreeRTOS component resolved the error
