### ISSUE TITLE
Bugs in Unified Host and nvm_interface

### ISSUE THREAD

**Issue by chris-mck** [Microchip-MPLAB-Harmony/bootloader#13]
The Unified Host .jar has a few things wrong with it:

* It does not check that the response received was for the correct command. E.g. if it issues a ERASE_FLASH (2) but receives a READ_BOOT_INFO (1) response, it continues anyway.
* (At least in USB mode) It does not issue any READ_CRC (4) command, although it logs "Validated" in the console.
* In UART mode, it seems to not process byte-stuffed data properly. It only reads the number of bytes for the expected response without any allowance for byte-stuffing. This makes it get out of sync with regard to SOH and EOT bytes.

Also, the Harmony-generated code in bootloader_nvm_interface has a bug where it does not memset the RAM buffer to 0xFF before starting to program pages. This will fill holes in the first page with zeros instead of ones, causing a CRC to fail if the range includes those holes.

**Comment by amitraddi** [comment]
Hi @chris-mck,
Thanks for reporting issue.

- We will investigate on this and fix it
- Currently READ_CRC command is not supported using the Unified Host. will be supported in future releases
- In Harmony 3 Unified Host tool should not be used for UART communication. UART Bootloader uses a python utility
https://github.com/Microchip-MPLAB-Harmony/bootloader/blob/master/tools/docs/readme_UnifiedHost_usb_device_hid.md#version-and-support-information

Regarding to the bootloader_nvm_interface can you please shed more information like file and line where you are expecting a memset

**Comment by chris-mck** [comment]
Hi @amitraddi,
I combined the USB HID and UART examples into one bootloader for my use-case. I wanted both interfaces to use the same protocol and chose to use AN1138 (USB) rather than the different protocol used in the UART example. I then wanted to check my UART changes worked, but I ended up modifying the python script to do this because of the issues above.


In bootloader_nvm_interface.c, it has `static T_NVM_DATA CACHE_ALIGN nvm_data` and initialises the `progAddr` and `prevAddr` members; it leaves the `CACHE_ALIGN buff` member "uninitialised" which means it is all zeros (because of `static`).

When it goes to write the first page of flash, either through `bootloader_AlignProgAddress()` or directly with `bootloader_NVMPageWrite()' (e.g. a short hex record), the buffer will have zeros at addresses that have not been loaded from a hex record. When running a CRC check, if hole addresses in the first page are included in the check, the check will fail because the hole addresses are expected to hold 0xFF and not 0x00.

Either the `buff` member needs to be initialised to all 0xFF's at the definition, or add an init function to use memset on the buffer before the first page is written. I added an init function in my code.

Alternatively, there is a work-around by making sure to exclude hole addresses in the first page from the CRC check.

**Comment by amitraddi** [comment]
Hi @chris-mck,
That is a good catch. we will update it in next Bootloader release

**Comment by jigneshmoradiya1** [comment]
Hi @chris-mck , Thanks for reporting this issue. This issue is fixed in the bootloader release v3.6.0

**Comment by chris-mck** [comment]
Thanks @jigneshmoradiya1 , I will close the issue.
