### ISSUE TITLE
Support for PIC32MZ?

### ISSUE THREAD

**Issue by MPukelis** [Microchip-MPLAB-Harmony/bootloader#2]
Currently cannot add the bootloader module to my project for pic32mz. 

When will UDP bootloader for PIC32MZ be supported? 

Regards!

**Comment by langetacuna** [comment]
+1 for the MZ bootloader.

**Comment by zzelevl** [comment]
Support for PIC32MZ UART bootloader will come at the end of the month.

**Comment by MPukelis** [comment]
> Support for PIC32MZ UART bootloader will come at the end of the month.

Thanks zzelevl, will there be options for UDP bootloader ?

**Comment by amitraddi** [comment]
Support for UDP bootloader will be added in early next year.

**Comment by LuisCRSousa** [comment]
+1 for the MZ bootloader.

**Comment by amitraddi** [comment]
@MPukelis @LuisCRSousa @langetacuna Bootloader now has support for PIC32M devices. v3.1.2

**Comment by langetacuna** [comment]
@amitraddi 
Thanks.  Will there be a release utilizing both boot flash pages for use as a bootloader update 'fail-safe' for the PIC32MZ?

**Comment by amitraddi** [comment]
@langetacuna Yes there will be support added for Fail-Safe update of Bootloader and also the Live-Update for application firmware in next release.

**Comment by langetacuna** [comment]
@amitraddi Great!  We have a product which is ready for release, but we were hoping to include the Fail-Safe version of the bootloader.  Do you anticipate that will be released soon? ;)

**Comment by langetacuna** [comment]
@amitraddi 
Sorry to keep bugging you, but I was hoping for Fail-Safe bootloader on the MZ soon... any news on that front?

**Comment by LuisCRSousa** [comment]
And USB support?

**Comment by MPukelis** [comment]
Hi all, 

Wanted to check if you have more accurate date for UDP bootloader release?  

Thank you

**Comment by amitraddi** [comment]
> 
> 
> @amitraddi
> Sorry to keep bugging you, but I was hoping for Fail-Safe bootloader on the MZ soon... any news on that front?

Hi 
Can you please provide some more details on what exactly you are looking for in Fail-Safe Bootloader solution?

**Comment by vlele94** [comment]
CAN bootloader for PIC32MK1024GPE Dev board

**Comment by amitraddi** [comment]
> Where can i get information/ sample code on CAN bootloader for PIC32MK1024GPE Dev board?

Hi @vlele94,
CAN Bootloader is currently not available as part of H3. It is planned for Q4 2020

**Comment by amitraddi** [comment]
UDP, USB and SDCARD Bootloaders are now available as part of v3.4.0 release.

You can find the bootloader application in below repositiories
https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_ethernet
https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_usb
https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_sdcard
