### ISSUE TITLE
UDP bootloader support pic32mz

### ISSUE THREAD

**Issue by MPukelis** [Microchip-MPLAB-Harmony/bootloader#5]
Hi, 

I wanted to check on the status of UDP bootloader support, last year I was told Q1 on 2020 was the planned release for UDP support, we have a product in development and plan to use this asap. 

It would be great if you have any updates?
Thanks

**Comment by amitraddi** [comment]
Hi @MPukelis
We are currently working on USB (HID & HOST MSD) and SDCARD bootloaders. We should be able to get the UDP bootloader delivered by end of July-2020

**Comment by amitraddi** [comment]
Hi @MPukelis,
UDP Bootloader is now available with v3.4.0
You can find the UDP bootloader applications here https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_ethernet
