### ISSUE TITLE
No Response from the device. Operation failed

### ISSUE THREAD

**Issue by LuisCRSousa** [Microchip-MPLAB-Harmony/bootloader#6]
I have a USB HID bootloader built with harmony 2 and I can upload code successfully.

Today I've replicated the bootloader with this latest harmony 3 and old PIC32 Bootloader Application V1.2 software. I can connect and erase the chip but when I click program, it sends the 'No Response from the device. Operation failed" message'

Also can't program with the new UnifiedHost-1.16.2 software

**Comment by amitraddi** [comment]
Hi @LuisCRSousa What is the device you are trying to run the bootloader on?
Can you share the the project so that we can have a look and help to provide solution

**Comment by LuisCRSousa** [comment]
> Hi @LuisCRSousa What is the device you are trying to run the bootloader on?
> Can you share the the project so that we can have a look and help to provide solution

PIC32MZ2064DAB288
Can you share an email for me to send the bootloader app?

**Comment by amitraddi** [comment]
> > Hi @LuisCRSousa What is the device you are trying to run the bootloader on?
> > Can you share the the project so that we can have a look and help to provide solution
> 
> PIC32MZ2064DAB288
> Can you share an email for me to send the bootloader app?
> amit.raddi@microchip.com

Meanwhile you can take a look at example application on PIC32MZ DAS https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_usb/tree/master/apps/usb_device_hid_bootloader/bootloader/firmware

> Is this new harmony 3 bootloader compatible with the old PIC32 Bootloader Application V1.2?
When you say a bootloader application is it the application you are programming using the bootloader or the bootloader it self?
If its bootloader, then i would prefer you to create the configuration fresh using the H3 framework

**Comment by amitraddi** [comment]
Hi @LuisCRSousa 
I just created a Bootloader for PIC32MZ2064DAB288 using H3 and was able to program an application successfully and run

**Comment by LuisCRSousa** [comment]
> Hi @LuisCRSousa
> I just created a Bootloader for PIC32MZ2064DAB288 using H3 and was able to program an application successfully and run

I've also been able to program the example bootloader/app using the UnifiedHost but the old PIC32 Bootloader Application V1.2 still fails. Is the old app not compatible with the new h3 bootloader?

**Comment by amitraddi** [comment]
> > Hi @LuisCRSousa
> > I just created a Bootloader for PIC32MZ2064DAB288 using H3 and was able to program an application successfully and run
> 
> I've also been able to program the example bootloader/app using the UnifiedHost but the old PIC32 Bootloader Application V1.2 still fails. Is the old app not compatible with the new h3 bootloader?

If you are using an old application with new H3 bootloader, please make sure you have selected the **Normalize Hex File** option in application project properties. See if this helps

![image](https://user-images.githubusercontent.com/45988337/88753068-f979a100-d178-11ea-81f4-4fda75c3e50a.png)

https://microchip-mplab-harmony.github.io/bootloader_apps_usb/apps/docs/readme_configure_application_pic32m.html#for-bootloading-the-application-with-usb_device_hid_bootloader

**Comment by LuisCRSousa** [comment]
I have that option selected and the problem still occurs using bootloader application V1.2.
It works with the same output .hex file using UnifiedHost.

Meanwhile we decided to continue using the H2 bootloader for our app as before.

**Comment by amitraddi** [comment]
> 
> 
> I have that option selected and the problem still occurs using bootloader application V1.2.
> It works with the same output .hex file using UnifiedHost.
> 
> Meanwhile we decided to continue using the H2 bootloader for our app as before.

Can you send your application project and bootloader project so that we can look at the issue

**Comment by LuisCRSousa** [comment]
[H3-btl-app-test.zip](https://github.com/Microchip-MPLAB-Harmony/bootloader/files/4994243/H3-btl-app-test.zip)

These are the btl and app i'm using to test for my app. Basically they are the harmony 3 bootloader usb hid example apps modified for my app as following:

- Changed the PIC32MZ DAS to PIC32MZ2064DAB288
- Re-generated harmony code

Bootloader:
- Commented btl trigger pattern code
- Added SW_1 button to trigger bootloader (line 122, active low)
- Added LED_BOTTOM_1 to indicate when my board are in bootloader (line 166-174)

App:
- Commented btl trigger pattern
- Added LED_BOTTOM_2 to indicate when my board are running the app (line 137-147)

I've also attached the image from PIC32 Bootloader Application V1.2 that I get when tryinh to program it.
![Anotação 2020-07-29 112359](https://user-images.githubusercontent.com/8472158/88790128-947d7580-d18f-11ea-82b1-89f49599819d.jpg)

**Comment by amitraddi** [comment]
> 
> 
> [H3-btl-app-test.zip](https://github.com/Microchip-MPLAB-Harmony/bootloader/files/4994243/H3-btl-app-test.zip)
> 
> These are the btl and app i'm using to test for my board. Basically they are the harmony 3 bootloader usb hid example apps modified for my board.
> 
>     * Changed the PIC32MZ DAS to PIC32MZ2064DAB288
> 
>     * Re-generated harmony code
> 
> 
> Bootloader:
> 
>     * Commented btl trigger pattern code
> 
>     * Deleted other pins used
> 
>     * Added SW_1 button to trigger bootloader (line 122, active low)
> 
>     * Added LED_BOTTOM_1 to indicate when my board are in bootloader (line 166-174)
> 
> 
> App:
> 
>     * Commented btl trigger pattern
> 
>     * Deleted other pins used
> 
>     * Added LED_BOTTOM_2 to indicate when my board are running the app (line 137-147)
> 
> 
> I've also attached the image from PIC32 Bootloader Application V1.2 that I get when trying to program it.
> ![Anotação 2020-07-29 112359](https://user-images.githubusercontent.com/8472158/88790128-947d7580-d18f-11ea-82b1-89f49599819d.jpg)

 I will look at the projects attached.

For Harmony 3 you have to use Unified Host Application. The v1.2 will not work.

**Comment by LuisCRSousa** [comment]
It's a custom board using the same processor.

Then the problem have been discovered. We have an app that we build based on the Bootloader Application v1.2 that's why I've been testing with the old app.

Thank you for all the help!

**Comment by amitraddi** [comment]
> 
> 
> It's a custom board using the same processor.
> 
> Then the problem have been discovered. We have an app that we build based on the Bootloader Application v1.2 that's why I've been testing with the old app.
> 
> Thank you for all the help!

Ok. YOu are welcome. Can you please close the issue if no resolution or inputs required
