### ISSUE TITLE
UART1 not working

### ISSUE THREAD

**Issue by khlee11** [Microchip-MPLAB-Harmony/bootloader#7]
Device: PIC32MK MCJ Curiosity Pro EVB
IDE: MPLAB X IDE v5.40, XC32 v2.50
BootLoader: Harmony3 UART_Bootloader (https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_uart/tree/master/apps/uart_bootloader)

Code data:
[test_App_firmware.zip](https://github.com/Microchip-MPLAB-Harmony/bootloader/files/5949056/test_App_firmware.zip)
[BTL_firmware.zip](https://github.com/Microchip-MPLAB-Harmony/bootloader/files/5949058/BTL_firmware.zip)

Issue:
UART1 does not work in the environment where the boot loader is applied.

Verification process:
1. I downloaded the boot loader to the chip. The boot loader is defined as UART2 as in the example.
And

2. Modify the example code of the test app (https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_uart/tree/master/apps/uart_bootloader/test_app/firmware/pic32mk_mcj_curiosity_pro.X) to further define UART1.

3. Then, run btl_host.py, the Bootloader Host app, and download the test APP to the board through the boot loader.

4. The sample code simply transmits the same data through UART1 and 2. 
5.  Connect the port by running terminal app to read the value sent from UART1 from PC.

6 However, no value is received.
Even in hardware, no signal is output through the UART1 Tx pin.
but UART2 communicates normally.

6. In the code, data is normally assigned to U1TXREG.

7. If the code of the same method is compiled without applying the boot loader and operated on the board, communication works normally.

Ask for help:
You won't find any problems in the code.
There seems to be no problem in code. Is it not working because of some problem?
We are looking for help in solving the problem.

**Comment by amitraddi** [comment]
@khlee11 We will look into the issue and get back to you

**Comment by amitraddi** [comment]
@khlee11 Below is the root cause and the solution for the issue you are facing
**Root Cause:**
As the bootloader code only uses UART2, The **plib_gpio.c** generated for bootloader will enable the Pins for UART2 and then perform a **IOLOCK** during initialization. Once the **IOLOCK** bit is set no other PIN configuration will work. Due to this when bootloader jumps into the application only UART2 works and UART1 does not as the pin configuration for UART1 in application code does not take effect.
The **IOL1WAY** Configuration bit (DEVCFG3<29>) blocks the **IOLOCK** bit from being cleared after it has been set once. This is the default setting which are programmed by bootloader.

![image](https://user-images.githubusercontent.com/45988337/107327281-e6a23a80-6ad2-11eb-8d9f-d7a66f622da6.png)

**Solution:**
For the issue to be resolved you need to disable the IOL1WAY setting in the bootloader project using MHC and regenerate the project as shown below.
![image](https://user-images.githubusercontent.com/45988337/107327887-dfc7f780-6ad3-11eb-90a1-0a0deff02440.png)

I tested on my setup using the release test_app(with UART1) and bootloader(UART2) and it works fine.

this issue will be resolved in next release of bootloader

**Comment by khlee11** [comment]
I think it was completely resolved thanks to your help.
We have confirmed that communication is working normally.
Thank you very much.

**Comment by amitraddi** [comment]
> 
> 
> I think it was completely resolved thanks to your help.
> We have confirmed that communication is working normally.
> Thank you very much.

You are welcome. i will close this issue as it is resolved.

**Comment by khlee11** [comment]
One more thing, but I would like to inquire.
![image](https://user-images.githubusercontent.com/78706932/107335717-a1dec980-6afb-11eb-951b-892e7430d923.png)

Are there any differences in compatibility according to the package version of MHC?

There was a difference between the example and the version, as shown in the attached image, and applying the latest version
When the code was regenerated and the boot loader was downloaded, the application program was not normally downloaded through the host program.
When I downloaded the boot loader with the same package version, it worked normally.

**Comment by amitraddi** [comment]
@khlee11 
Ideally It should not matter. as the bootloader was tested with older csp and core version you see the difference here.
I did try with latest version of csp, core and MHC and did not finad any issues.
what is the error you get When you say "application program was not normally downloaded"

**Comment by khlee11** [comment]
If you apply the boot loader with the code created with the latest version and process the host program to download the application program,
As shown in the image, it was operated with no response.
![image](https://user-images.githubusercontent.com/78706932/107338135-8d500080-6afe-11eb-8399-89de370706b1.png)

If the version was correct, it was downloaded normally.
![image](https://user-images.githubusercontent.com/78706932/107338274-b2dd0a00-6afe-11eb-8a57-87eafe3ddb4b.png)

**Comment by amitraddi** [comment]
This is strange, Because i am not able to reproduce this issue on my side. I will further investigate it.
One hint, i am not sure it may work, try to power cycle the device when you program the bootloader with latest version for first time
But i hope you are unblocked with the recommended versions.

**Comment by khlee11** [comment]
Please contact us regarding boot loader application.
Much is being solved with your help.
It was a lot of difficulties when I first encountered harmony3 and pic32 and used it.

If we apply a bootloader, is it not possible to use UART interrupts?
When I enable UART Interrupt (RX), the code is not executed.
The main loop does not rotate.
Timer interrupt is executed normally.
Am I wrong with the settings?

**Comment by amitraddi** [comment]
> 
> 
> Please contact us regarding boot loader application.
> Much is being solved with your help.
> It was a lot of difficulties when I first encountered harmony3 and pic32 and used it.
> 
> If we apply a bootloader, is it not possible to use UART interrupts?
> When I enable UART Interrupt (RX), the code is not executed.
> The main loop does not rotate.
> Timer interrupt is executed normally.
> Am I wrong with the settings?
> 
> In MHC, I simply activated the function and generated an interrupt code.

Thanks for feedback.

The H3 UART bootloader is designed to work only in UART non interrupt mode. If you want to use UART interrupts then you have to update the bootloader code to adapt to that.

**Comment by khlee11** [comment]
If there are multiple UARTs on the chip, UART2 is used as a boot loader.
Is it correct that UART1 also cannot operate as an interrupt?

So, if I can't modify the H3 bootloader, should I run the UART in a polling way?
Are there any other restrictions other than UART interrupt when using the H3 boot loader?

**Comment by amitraddi** [comment]
Yes, By default any UART instance used by the bootloader core should be in non interrupt mode.
Note that the bootloader_Task() once called never returns, which means no other task can run cooperatively with bootloader

**Comment by khlee11** [comment]
Thanks for your help.
There is no development that can be done easily.

**Comment by khlee11** [comment]
I have other questions.
I am writing UART transmission/reception by polling method.
Transmission seems to be fine in PIC.
However, there is a problem in receiving processing.
It appears to be a phenomenon caused by RX FIFO on the UART module of PIC32MK.
RX FIFO is 8-Level and up to 8 bytes can be received without problem.
However, if 9 bytes are transmitted, reception processing is performed at the first time, but reception processing is not performed at all after that.

I try to receive 8 bytes 3 times, and finally, after receiving 9 bytes, I cannot receive it.
![image](https://user-images.githubusercontent.com/78706932/107481379-69a1be80-6bc1-11eb-8895-7947f5c22830.png)

What causes this phenomenon?
No matter how simple you modify the code, it is the same.
The code I received and processed is as follows.
![image](https://user-images.githubusercontent.com/78706932/107481131-0d3e9f00-6bc1-11eb-84a4-f471e4db814a.png)

**Comment by amitraddi** [comment]
> 
> 
> I have other questions.
> I am writing UART transmission/reception by polling method.
> Transmission seems to be fine in PIC.
> However, there is a problem in receiving processing.
> It appears to be a phenomenon caused by RX FIFO on the UART module of PIC32MK.
> RX FIFO is 8-Level and up to 8 bytes can be received without problem.
> However, if 9 bytes are transmitted, reception processing is performed at the first time, but reception processing is not performed at all after that.
> 
> I try to receive 8 bytes 3 times, and finally, after receiving 9 bytes, I cannot receive it.
> ![image](https://user-images.githubusercontent.com/78706932/107481379-69a1be80-6bc1-11eb-8895-7947f5c22830.png)
> 
> What causes this phenomenon?
> No matter how simple you modify the code, it is the same.
> The code I received and processed is as follows.
> ![image](https://user-images.githubusercontent.com/78706932/107481131-0d3e9f00-6bc1-11eb-84a4-f471e4db814a.png)

Can you please post this issue in https://github.com/Microchip-MPLAB-Harmony/csp.

**Comment by khlee11** [comment]
Okay. Moved and uploaded again

**Comment by khlee11** [comment]
Okay. Moved and uploaded again
