### ISSUE TITLE
NVM problem

### ISSUE THREAD

**Issue by khlee11** [Microchip-MPLAB-Harmony/bootloader#8]
I need help.

I don't know if this has anything to do with the boot loader.

I would like to apply the NVM driver to my program to utilize a specific space of flash as my data storage space.
However, even with the NVM example, the data is not written.
Do I need to modify the boot loader to fix this problem?
Could there be an effect of the NVM in the boot loader?

    uint32_t rdat[2]={0,0};
    uint32_t  dat=121212;

    printf("%d dataB: %d \n",xferDone, dat);
    NVM_WordWrite(dat, 0x9d070000U);
    dat=0;
    while(xferDone == false);
    xferDone = false;
    printf("%d dataW: %d \n",xferDone, dat);    
    NVM_Read(rdat, 1, 0x9d070000U);
    printf("dataR1: %d \n", rdat[0]);

I just performed a function to write and read data
No data could be confirmed.

**Comment by amitraddi** [comment]
@khlee11 Do you still see this issue?

**Comment by khlee11** [comment]
> @khlee11 Do you still see this issue?

I'm not exactly sure what the problem is.
But I found a way to do what I want.

When addressing the NVM in units of 1, the data was not stored as desired.
However, when I changed the address to 4 units, it worked normally.
I think it's probably because it's 32-bit data.
